<div class="page-content">
	<!-- Breadcrumb Section -->
	<section class="breadcrumb-section breadcrumb-section-white section-box" style="background-image: url(/images/breadcrumb-contact.jpg)">
		<div class="container">
				<div class="breadcrumb-inner">
					<h1>Contact</h1>
					<ul class="breadcrumbs">
						<li>
							<a class="breadcrumbs-1" href="/">Accueil</a>
							/ Contact
						</li>
					</ul>
				</div>	
		</div>
	</section>
	<!-- End Breadcrumb Section -->
	<!-- Contact Section -->
	<section class="contact-section section-box">
		<div class="container">
				<div class="contact-content">
					<div class="row contact-quote">
						<div class="col-12 text-center">
							<h5>
								<b>Parce que rien ne vaut la rencontre et l’échange, ensemble, étudions votre demande.</b>
								<br/>
								Je vous laisse ici me décrire brièvement vos besoins et je vous contacte au plus vite pour trouver un terrain d’entente.
								<br/><br/>
							</h5>
						</div>
					</div>
					<div class="row">
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12 d-flex align-items-center">
							<div class="contact-details text-center">
								<div class="contact-info text-left">
									<div class="contact-inner">
										<p class="center"><i class="zmdi zmdi-map"></i>14, avenue Mondenard 47600 NERAC</p>
										<p class="center"><i class="zmdi zmdi-phone"></i>05 53 65 16 29</p>
										<p class="center"><i class="zmdi zmdi-email"></i>Librairie : <a href="librairie@au-plafond.fr">librairie@au-plafond.fr</a></p>
										<p class="center"><i class="zmdi zmdi-email"></i>Atelier : <a href="contact@ellestmanuelle.fr">contact@ellestmanuelle.fr</a></p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
							<div class="contact-details text-center">
								<img src="/images/uploads/vue de Nérac.jpg"/>
							</div>
						</div>
					</div>
				</div>
		</div>
	</section>
	<!-- End Contact Section -->
</div>